name: Merge waka readme in profile

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Waka content
        run: |
          url="https://raw.githubusercontent.com/eskopp/eskopp/refs/heads/main/Readme.md"
          content=$(curl -s "$url")
          # Extract content from <!--START_SECTION:waka--> to the end of the file
          waka_section=$(echo "$content" | sed -n '/<!--START_SECTION:waka-->/,$p')

          # Escape special characters and newlines for sed
          waka_section_escaped=$(echo "$waka_section" | sed 's/[\/&]/\\&/g; s/$/\\n/g')

          # Insert the waka_section into the profile/README.md, replacing from <!--START_SECTION:waka--> to the end
          readme_file="profile/README.md"
          sed -i "/<!--START_SECTION:waka-->/,\$c\<!--START_SECTION:waka-->\n$waka_section_escaped" "$readme_file"

      - name: Commit and Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.name "$(echo 'ZXNrb3Bw' | base64 --decode)"
          git config --local user.email "$(echo 'c2tvcHAuZXJpa0BnbWFpbC5jb20=' | base64 --decode)"
          git add profile/README.md
          git commit -m "Update README.md with WakaTime stats"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
