name: Merge waka readme in profile

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'  

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Waka content
        run: |
            file_content=$(cat Readme.md)
            cd profile
            echo "$file_content" > Readme.md

      - name: Commit and Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.name "$(echo 'ZXNrb3Bw' | base64 --decode)"
          git config --local user.email "$(echo 'c2tvcHAuZXJpa0BnbWFpbC5jb20=' | base64 --decode)"
          git add profile/Readme.md
          git commit -m "Update Readme.md"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
